// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxELsJDr1SkbFd_XjtKZ6Xcp69OZQk1uY',
    appId: '1:214977947385:ios:e375d97157470a0684e428',
    messagingSenderId: '214977947385',
    projectId: 'cozyshop-bdc9e',
    storageBucket: 'cozyshop-bdc9e.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppProject',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtozPxj4ujORSe-3rB5UFHP0ISKmjymzM',
    appId: '1:214977947385:android:ada64d2bf469b6ec84e428',
    messagingSenderId: '214977947385',
    projectId: 'cozyshop-bdc9e',
    storageBucket: 'cozyshop-bdc9e.firebasestorage.app',
  );

}